name: Deploy to fly.io
on:
  push:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  repository_dispatch:
    types: [deploy]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v3
        with:
          ref: deploy
      - name: Save fly.toml to another directory
        run: cp fly.toml /tmp/fly.toml
      - name: Clone RSSHub repository
        uses: actions/checkout@v3
        with:
          repository: DIYgod/RSSHub
          ref: master
      - name: Copy fly.toml into RSSHub repository
        run: cp /tmp/fly.toml ./fly.toml
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to fly.io with remote only option
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
